char *getVal(char *, char *);
long getClientID(char *);
long getProtocol(char *);
long getVersion(char *);
long getStorageType(char *);
long getIopsMax(char *);
long getIopsMin(char *);
long getThroughputMax(char *);
long getThroughputMin(char *);
long getUnusedBandwidth(char *);
